parameters:
    tom32i_simple_security.manager.user.class:      Tom32i\Bundle\SimpleSecurityBundle\Service\UserManager
    tom32i_simple_security.manager.voucher.class:   Tom32i\Bundle\SimpleSecurityBundle\Service\VoucherManager
    tom32i_simple_security.manager.mail.class:      Tom32i\Bundle\SimpleSecurityBundle\Service\MailManager

services:
    # User manager
    tom32i_simple_security.manager.user:
        class: "%tom32i_simple_security.manager.user.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
            - "@security.authentication.provider.voucher"
            - "@tom32i_simple_security.manager.mail"
            - "%tom32i_simple_security.parameters.user_class%"

    # Mail manager:
    tom32i_simple_security.manager.mail:
        class:  "%tom32i_simple_security.manager.mail.class%"
        arguments:
            - "@mailer"
            - "@translator"
            - "@templating"
            - "@router"
            - "%tom32i_simple_security.parameters.mailer_from%"
