parameters:
    tom32i_simple_security.routing_loader.class: Tom32i\Bundle\SimpleSecurityBundle\Routing\SecurityLoader
    tom32i_simple_security.authenticator.class:  Tom32i\Bundle\SimpleSecurityBundle\Service\Authenticator

services:
    # Routing Loader
    tom32i_simple_security.routing_loader:
        class: "%tom32i_simple_security.routing_loader.class%"
        tags:
            - { name: routing.loader }

    # Authenticator
    tom32i_simple_security.authenticator:
        class: "%tom32i_simple_security.authenticator.class%"
        arguments:
            - "@security.encoder_factory"
