services:
    # User manager
    tom32i_simple_security.manager.user:
        class: Tom32i\Bundle\SimpleSecurityBundle\Service\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
            - "@router"
            - "@security.password_encoder"
            - "@elao_voucher_authentication.voucher_provider.default"
            - "@tom32i_simple_security.manager.mail"
            #- "%tom32i_simple_security.parameters.user_class%"

    # Mail manager:
    tom32i_simple_security.manager.mail:
        class:  Tom32i\Bundle\SimpleSecurityBundle\Service\MailManager
        arguments:
            - "@mailer"
            - "@translator"
            - "@templating"
            - "%tom32i_simple_security.parameters.mailer_from%"
