parameters:
    tom32i_simple_security.subscriber.doctrine.password.class:       Tom32i\Bundle\SimpleSecurityBundle\ORM\Doctrine\Subscriber\PasswordSubscriber
    tom32i_simple_security.subscriber.doctrine.class_metadata.class: Tom32i\Bundle\SimpleSecurityBundle\ORM\Doctrine\Subscriber\ClassMetadataSubscriber
    tom32i_simple_security.subscriber.kernel.voucher_trash.class:    Tom32i\Bundle\SimpleSecurityBundle\Event\Subscriber\VoucherTrashSubscriber

services:
    # Doctrine Password Subscriber
    tom32i_simple_security.subscriber.doctrine.password:
        class: "%tom32i_simple_security.subscriber.doctrine.password.class%"
        arguments:
            - "@tom32i_simple_security.authenticator"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Doctrine Class Metadata Subscriber
    tom32i_simple_security.subscriber.doctrine.class_metadata:
        class: "%tom32i_simple_security.subscriber.doctrine.class_metadata.class%"
        arguments:
            - "%tom32i_simple_security.parameters.user_class%"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
