parameters:
    tom32i_simple_security.form.user_password.class: Tom32i\Bundle\SimpleSecurityBundle\Form\Type\UserPasswordType
    tom32i_simple_security.form.forgot_password.class: Tom32i\Bundle\SimpleSecurityBundle\Form\Type\ForgotPasswordType

services:
    # Forgot password
    tom32i_simple_security.form.forgot_password:
        class:  %tom32i_simple_security.form.forgot_password.class%
        tags:
            - { name: form.type, alias: forgot_password }

    # Change password
    tom32i_simple_security.form.user_password:
        class:  %tom32i_simple_security.form.user_password.class%
        arguments:
            - %tom32i_simple_security.parameters.user_class%
        tags:
            - { name: form.type, alias: user_password }
