services:
    # Forgot password
    tom32i_simple_security.form.forgot_password:
        class:  Tom32i\Bundle\SimpleSecurityBundle\Form\Type\ForgotPasswordType
        tags:
            - { name: form.type }

    # Change password
    tom32i_simple_security.form.user_password:
        class:  Tom32i\Bundle\SimpleSecurityBundle\Form\Type\UserPasswordType
        arguments:
            - "%tom32i_simple_security.parameters.user_class%"
        tags:
            - { name: form.type }
